title: Nadia Anuar
logo: "/images/photo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst with 1+ year of experience performing data analysis tasks and building dashboards/reports in agile fintech and service marketplace companies. 
  <br><br>
    
  5-month industrial training as a data science intern at DHL Asia Pacific Innovation Centre.
  <br><br>
  
  4+ years of management/administration experience in retail. 
  <br><br>
  
  <a href="https://www.linkedin.com/in/nadiaanuarr/" target="_blank"> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/600px-LinkedIn_logo_initials.png" alt="LinkedIn" width="40" height="40"/> </a> 
  <a href="https://github.com/nadiaanuarr/" target="_blank"> <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="Github" width="40" height="40"/> </a>
  <br><br>
  
theme: jekyll-theme-minimal

