title: Nadia Anuar | Data Scientist Trainee 
logo: "/images/photo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm on the lookout for a permanent data scientist role. 
  <br><br>
    
  I have completed a 5-month industrial training as a data science intern at DHL Asia Pacific Innovation Centre.
  Additionally, I have 5-years customer-oriented experience, management and technical skills in retail with a keen interest in data and AI technology-driven industries.
  <br><br>

  <a href="https://www.linkedin.com/in/nadiaanuarr/" target="_blank"> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/600px-LinkedIn_logo_initials.png" alt="LinkedIn" width="40" height="40"/> </a> 
  <a href="https://github.com/nadiaanuarr/" target="_blank"> <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="Github" width="40" height="40"/> </a>
  
theme: jekyll-theme-minimal

